# Generated by Django 3.2.19 on 2023-06-16 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('goods', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartinfo',
            options={'verbose_name': 'cart', 'verbose_name_plural': 'cart'},
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodsinfo', verbose_name='goods'),
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo', verbose_name='user'),
        ),
    ]
